apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: template
  labels:
    name: app
  annotations:
    secret.reloader.stakater.com/reload: "env"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/template:SHORT_SHA
          envFrom:
            - secretRef:
                name: env
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
